### ISSUE TITLE
Such item cards cannot be opened

### ISSUE THREAD

**Issue by Apriawanto15** [Qbox-project/qbx_idcard#5]
### Summary

id card does not appear or cannot be opened

### Reproduction

I tried again to do a clean install, and found when after creating a character there is a notification about adding items such as id cards and such that does not appear the name or anything when it opens it

### Expected behavior

![image](https://github.com/Qbox-project/qbx_idcard/assets/58946086/0a227ecf-1593-427c-95e2-73620fabbc4e)

### Actual behavior

.

### Additional context

.

### Last Updated

.

### Custom Resources

.

### Resource Rename

qbx_idcard

**Comment by MafewTM** [comment]
When they are in your task bar, press the number twice. So if your ID is in slot 5, press 5 twice

**Comment by Apriawanto15** [comment]
I have tried it, I have moved it to several slots 1 2 3 4 5, it still does not appear as before
